import hero from "/assets/images/hero.jpeg";

export const heroImg = hero;

import hmv from "/assets/videos/hero.mp4";
import smallmv from "/assets/videos/smallHero.mp4";
import highlightFirstmv from "/assets/videos/highlight-first.mp4";
import highlightSectmv from "/assets/videos/hightlight-third.mp4";
import highlightThirdmv from "/assets/videos/hightlight-sec.mp4";
import highlightFourthmv from "/assets/videos/hightlight-fourth.mp4";
import exploremv from "/assets/videos/explore.mp4";
import framemv from "/assets/videos/frame.mp4";
import zoom from "/assets/videos/zoom.mp4";
import silent from "/assets/videos/silent-mode.mp4";

import apple from "/assets/images/apple.svg";
import search from "/assets/images/search.svg";
import bag from "/assets/images/bag.svg";
import watch from "/assets/images/watch.svg";
import right from "/assets/images/right.svg";
import replay from "/assets/images/replay.svg";
import play from "/assets/images/play.svg";
import pause from "/assets/images/pause.svg";

import yellow from "/assets/images/yellow.jpg";
import blue from "/assets/images/blue.jpg";
import white from "/assets/images/white.jpg";
import black from "/assets/images/black.jpg";
import explore1 from "/assets/images/explore1.jpg";
import explore2 from "/assets/images/explore2.jpg";
import chip from "/assets/images/chip.jpeg";
import frame from "/assets/images/frame.png";
import iguana from "/assets/images/iguana.jpg";
import ultrawideMacro from "/assets/images/ultrawide-macro.jpg";
import ultrawide13mm from "/assets/images/ultrawide-13mm.jpg";
import main24mm from "/assets/images/main-24mm.jpg";
import main28mm from "/assets/images/main-28mm.jpg";
import main35mm from "/assets/images/main-35mm.jpg";
import telephoto48mm from "/assets/images/telephoto-48mm.jpg";
import telephoto120mm from "/assets/images/telephoto-120mm.jpg";
import mainCam from "/assets/images/main-cam.jpg";
import gigabits from "/assets/images/gigabits.jpg";
import foundation from "/assets/images/foundation.jpg";
import playback from "/assets/images/playback.png";
import emergency from "/assets/images/emergency.jpg";
import makeadifference from "/assets/images/make-a-diferrence.jpg";
import style1 from "/assets/images/style1.jpg";
import style2 from "/assets/images/style2.jpg";
import style3 from "/assets/images/style3.jpg";
import appleAirPods from "/assets/images/iPhone-airpods.jpg";
import iconTrade from "/assets/images/icon-trade.png";
import iconApple from "/assets/images/icon-apple.png";
import iconCarrier from "/assets/images/icon-carrier.png";
import iconDelivery from "/assets/images/icon-delivery.png";
import iconSpecialist from "/assets/images/icon-specialist.png";
import iconPersonal from "/assets/images/icon-personal.png";
import iconShopping from "/assets/images/icon-shopping.png";
import iPhoneBlack from "/assets/images/iphone-black.jpg";
import iPhonePink from "/assets/images/iphone-pink.jpg";
import iconA17 from "/assets/images/icon_a17.png";
import iconA16 from "/assets/images/icon_a16.png";
import iconTripleCamera from "/assets/images/icon_3camera.png";
import iconDualCamera from "/assets/images/icon_2camera.png";
import iconBattery from "/assets/images/icon_battery.png";

export const heroVideo = hmv;
export const smallHeroVideo = smallmv;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFourthVideo = highlightFourthmv;
export const exploreVideo = exploremv;
export const frameVideo = framemv;
export const zoomVideo = zoom;
export const silentVideo = silent;

export const appleImg = apple;
export const searchImg = search;
export const bagImg = bag;
export const watchImg = watch;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const explore1Img = explore1;
export const explore2Img = explore2;
export const chipImg = chip;
export const frameImg = frame;
export const iguanaImg = iguana;
export const ultrawideMacroImg = ultrawideMacro;
export const ultrawide13mmImg = ultrawide13mm;
export const main24mmImg = main24mm;
export const main28mmImg = main28mm;
export const main35mmImg = main35mm;
export const telephoto48mmImg = telephoto48mm;
export const telephoto120mmImg = telephoto120mm;
export const mainCamImg = mainCam;
export const gigabitsImg = gigabits;
export const foundationImg = foundation;
export const playbackImg = playback;
export const emergencyImg = emergency;
export const makeadifferenceImg = makeadifference;
export const style1Img = style1;
export const style2Img = style2;
export const style3Img = style3;
export const appleAirPodsImg = appleAirPods;
export const iconTradeImg = iconTrade;
export const iconAppleImg = iconApple;
export const iconCarrierImg = iconCarrier;
export const iconDeliveryImg = iconDelivery;
export const iconSpecialistImg = iconSpecialist;
export const iconPersonalImg = iconPersonal;
export const iconShoppingImg = iconShopping;
export const iPhoneBlackImg = iPhoneBlack;
export const iPhonePinkImg = iPhonePink;
export const iconA17Img = iconA17;
export const iconA16Img = iconA16;
export const iconTripleCameraImg = iconTripleCamera;
export const iconDualCameraImg = iconDualCamera;
export const iconBatteryImg = iconBattery;
